[package]
name = "snowflake-adbc-driver-poc"
version = "0.1.0"
edition = "2024"

[dependencies]
adbc_core = "0.21.0"
adbc_driver_manager = "0.21.0"
arrow = { version = "57.0.0", features = ["prettyprint"] }
arrow-array = "57.0.0"
